### ISSUE TITLE
exception when finding an order

### ISSUE THREAD

**Issue by rkjamvi** [ShippingEasy/shipping_easy-php#4]
Hi,

Please see below code, (100035142 is order number which exists in our store):

$order = new ShippingEasy_Order();
$order->find(100035142);

Above script giving below:

Fatal error: Uncaught exception 'ShippingEasy_InvalidRequestError' with message 'Order not found.' in /home/pushfors/public_html/app/ajax_files/lib/ShippingEasy/ApiRequestor.php:61 Stack trace: #0 /home/pushfors/public_html/app/ajax_files/lib/ShippingEasy/ApiRequestor.php(102): ShippingEasy_ApiRequestor->handleApiError('{"errors":[{"me...', 404, Array) #1 /home/pushfors/public_html/app/ajax_files/lib/ShippingEasy/ApiRequestor.php(44): ShippingEasy_ApiRequestor->_interpretResponse('{"errors":[{"me...', 404) #2 /home/pushfors/public_html/app/ajax_files/lib/ShippingEasy/Object.php(8): ShippingEasy_ApiRequestor->request('get', '/api/orders/876', NULL, NULL, NULL, NULL) #3 /home/pushfors/public_html/app/ajax_files/lib/ShippingEasy/Order.php(17): ShippingEasy_Object->request('get', '/api/orders/876') #4 /home/pushfors/public_html/app/ajax_files/cron_shipping.php(22): ShippingEasy_Order->find(876) #5 {main} thrown in /home/pushfors/public_html/app/ajax_files/lib/ShippingEasy/ApiRequestor.php on line 61

**Comment by greggeasy** [comment]
The problem is that you are using the order number from your store. You instead need to use the ShippingEasy order ID, which is returned in a JSON hash on the create, as described on this page: http://shippingeasy.readme.io/docs/creating-an-order-1

**Comment by rkjamvi** [comment]
Hi,

Thanks for the quick reply, I first tried creating a test order, but it was
giving error too, thats why i tried to find an order, I just enable create
order code and see now the exception.

http://app.pushforsnacks.com/ajax_files/cron_shipping.php

Thanks for the help

On Tue, Jul 14, 2015 at 12:02 AM, greggeasy <notifications@github.com>
wrote:

> The problem is that you are using the order number from your store. You
> instead need to use the ShippingEasy order ID, which is returned in a JSON
> hash on the create, as described on this page:
> http://shippingeasy.readme.io/docs/creating-an-order-1
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ShippingEasy/shipping_easy-php/issues/4#issuecomment-121023949>
> .
>



-- 
Kind regards,
Rizwan Karim Jamvi

Web & IT Entrepreneur
Skype = rkjamvi
Follow me @rkjamvi
